name: Deploy Cloud Function

on:
  push:
    branches:
      - main

jobs:
  deploy-function:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Zip Cloud Function code
        run: zip function.zip ./index.js ./package.json

      - name: Decode JSON secret
        id: decode_json
        run: |
          echo "GCP_SA_KEY=$(echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode)" >> $GITHUB_ENV
      
      - name: auth Google Cloud CLI
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.GCP_SA_KEY }}
          
      - name: Setup Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true
      
      - name: Upload Zip to Cloud Storage
        run: gsutil cp function.zip gs://${{ secrets.GCS_BUCKET }}/${{ github.sha }}-function.zip
